### ISSUE TITLE
Unable to Read Data

### ISSUE THREAD

**Issue by zagdrath** [petar-dambovaliev/s7#4]
This is my code and this how my db is in TIA Portal. I am not exactly sure if I am doing something wrong.

[Image of DB in TIA](https://prnt.sc/i0H3jm9jgoSQ)
[Image of Error](https://prnt.sc/J9Rp97FBfUo3)

```rust
extern crate s7;

use s7::{client::Client, field::Bool, tcp, transport::Connection};
use std::net::{IpAddr, Ipv4Addr};
use std::time::Duration;

fn main() {
    let addr = Ipv4Addr::new(192, 168, 1, 187);
    let mut opts = tcp::Options::new(IpAddr::from(addr), 0, 1, Connection::PG);

    opts.read_timeout = Duration::from_secs(2);
    opts.write_timeout = Duration::from_secs(2);

    let t = tcp::Transport::connect(opts).unwrap();
    let mut cl = Client::new(t).unwrap();

    let buffer = &mut vec![0u8; Bool::size() as usize];
    let db = 1;

    // the offset in the PLC is represented by a float
    // the difit on the left is the index within the block
    // the digit after the decimal point is only important for the `Bool` to be able to change the relevant bit
    // we don't need after
    let offset = 2.4;

    // Since this is a boolean field, we are going to get back 1 byte
    cl.ag_read(db, offset as i32, Bool::size(), buffer).unwrap();
}
```

**Comment by PecTify** [comment]
It looks like the offset of 2.4 is too big. For E_Stop, it should be 0.0 and Yellow_Light 0.1

**Comment by zagdrath** [comment]
Using an offset of 0.0 or 0.1 still leaves me with the same issue. When trying to write using the code below it gives me [this error](https://prnt.sc/xmHa95E0lCBw). Any help would be greatly appreciated.

```rust
extern crate s7;

use s7::field::Fields;
use s7::{client::Client, field::Bool, tcp, transport::Connection};
use std::net::{IpAddr, Ipv4Addr};
use std::time::Duration;

fn main() {
    let addr = Ipv4Addr::new(192, 168, 1, 187);
    let mut opts = tcp::Options::new(IpAddr::from(addr), 0, 1, Connection::PG);

    opts.read_timeout = Duration::from_secs(2);
    opts.write_timeout = Duration::from_secs(2);

    let t = tcp::Transport::connect(opts).unwrap();
    let mut cl = Client::new(t).unwrap();

    let buffer = &mut vec![0u8; Bool::size() as usize];
    let db = 1;

    // the offset in the PLC is represented by a float
    // the difit on the left is the index within the block
    // the digit after the decimal point is only important for the `Bool` to be able to change the relevant bit
    // we don't need after
    let offset = 0.1;

    // Since this is a boolean field, we are going to get back 1 byte
    // cl.ag_read(db, offset as i32, Bool::size(), buffer).unwrap();

    let mut lights = Bool::new(db, offset, buffer.to_vec()).unwrap();

    lights.set_value(true);

    let fields: Fields = vec![Box::new(lights)];

    // save back the changed values
    for field in fields.iter() {
        cl.ag_write(
            field.data_block(),
            field.offset(),
            field.to_bytes().len() as i32,
            field.to_bytes().as_mut(),
        )
        .unwrap();
    }
}
```

**Comment by zagdrath** [comment]
After looking through the code I can see that the exact error I am getting is `error::ISO_INVALID_DATA_SIZE`.

**Comment by PecTify** [comment]
You may need to disable Optimized block access in the  [DB configuration](https://prnt.sc/NTz86XR_q1Me).

**Comment by zagdrath** [comment]
Still getting that same error unfortunately. Is there any other settings that might need to be configured?

**Comment by PecTify** [comment]
You can also check if the "Full access" and the Check "Permit access with PUT/GET ..." is set in the PLC [properties](https://prnt.sc/93TvwJ3Ip4Zs).

**Comment by zagdrath** [comment]
> You can also check if the "Full access" and the Check "Permit access with PUT/GET ..." is set in the PLC [properties](https://prnt.sc/93TvwJ3Ip4Zs).

I have already made sure those are checked. I have no clue what else could be causing this issue.

**Comment by petar-dambovaliev** [comment]
Hey, sorry for the super late response.
I wrote this library when i was working at a company that had to access this type of hardware.
I've been long gone from there and have no way to test or debug, as i don't have the hardware.

**Comment by zagdrath** [comment]
Turns out I forgot that I had a password enabled on the PLC itself and that was preventing communication, @PecTify thank you very much for the help.
